apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: db-snipeit-storage
  resources:
    requests:
      storage: 4Gi
status: {}
