apiVersion: v1
kind: PersistentVolume   
metadata:
  name: db-pv    
  namespace: snipeit
spec:
  capacity:
    storage: 4Gi          
  accessModes:
  - ReadWriteOnce         
  storageClassName: db-snipeit-storage
  hostPath:
    path: "/tmp"
