apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snipeit-ingress
  namespace: snipeit
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /snipeit
            pathType: Prefix
            backend:
              service:
                name: snipeit
                port:
                  number: 8080
