apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: snipeit
spec:
  addresses:
  - 172.23.8.60-172.23.8.60
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: 
spec:
  ipAddressPools:
  - default
