apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o deployment
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: snipeit
  name: snipeit
  namespace: snipeit
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: snipeit
