apiVersion: v1
kind: PersistentVolume   
metadata:
  name: snipeit-pv      
spec:
  capacity:
    storage: 8Gi          
  accessModes:
  - ReadWriteOnce         
  storageClassName: local-storage
  hostPath:
    path: "/tmp/data02"
    type: "DirectoryOrCreate"
 
