apiVersion: v1
kind: PersistentVolume   
metadata:
  name: snipeit-pv-test   
  namespace: snipeit
spec:
  capacity:
    storage: 400Mi          
  accessModes:
  - ReadWriteOnce         
  storageClassName: local-storage
  hostPath:
    path: "/tmp/data02"
    type: "DirectoryOrCreate"
 
